apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: logoutput
  ports:
  - port: 1234
    name: logoutput-port
    protocol: TCP
    targetPort: 3000
  - port: 2345
    name: pingpong-port
    protocol: TCP
    targetPort: 3500
