apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todoapp-config
data:
  listen-url: http://0.0.0.0:3000
  photo-delay: "600000"
  photo-file: images/photo.jpg
  service-url: http://todoapp-svc:2345/todos
  picsum-url: https://picsum.photos/1200