apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: logpingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logpingpong
  template:
    metadata:
      labels:
        app: logpingpong
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-config
            items:
              - key: file
                path: information.txt
      containers:
        - name: logoutput
          image: rjantp/kubernetessubmissions:ex2.5a
          volumeMounts:
            - name: config-volume
              mountPath: /var/tmp
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: message
        - name: pingpong
          image: rjantp/kubernetessubmissions:ex2.7p7
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3500"

