apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: logpingpong-svc
spec:
  type: ClusterIP
  selector:
    app: logpingpong
  ports:
  - port: 1234
    name: logoutput-port
    protocol: TCP
    targetPort: 3000
  - port: 2345
    name: pingpong-port
    protocol: TCP
    targetPort: 3500
