# ==========================================================
# ConfigMap
# ==========================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: logoutput-config
data:
  message: "hello world"
  file: "this text is from file"
---
# ==========================================================
# Deployment
# ==========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logpingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logpingpong
  template:
    metadata:
      labels:
        app: logpingpong
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-config
            items:
              - key: file
                path: information.txt 
      containers:
        - name: logoutput
          image: rjantp/kubernetessubmissions:ex3.3l
          volumeMounts:
            - name: config-volume
              mountPath: /var/tmp
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: message
        - name: pingpong
          image: rjantp/kubernetessubmissions:ex3.3p
          env:
            - name: PORT
              value: "3500"
---
# ==========================================================
# Service
# ==========================================================
apiVersion: v1
kind: Service
metadata:
  name: logpingpong-svc
spec:
  type: ClusterIP
  selector:
    app: logpingpong
  ports:
  - port: 1234
    name: logoutput-port
    protocol: TCP
    targetPort: 3000
  - port: 2345
    name: pingpong-port
    protocol: TCP
    targetPort: 3500
---
# ==========================================================
# Gateway
# ==========================================================
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: logpingpong-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 8081
---
# ==========================================================
# HTTPRoute
# ==========================================================
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: logoutput-route
spec:
  parentRefs:
  - kind: Gateway
    name: logpingpong-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: logpingpong-svc
      port: 1234
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pingpong-route
spec:
  parentRefs:
  - kind: Gateway
    name: logpingpong-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    backendRefs:
    - name: logpingpong-svc
      port: 2345
